service: auth-service

plugins:
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}

resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}

functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - http:
          method: POST
          path: /users
          cors: true

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn 

package:
  excludeDevDependencies: true
  exclude:
    - tests/**
    - jest.config.ts  