service: techs-service

plugins:
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    TECHS_TABLE_NAME: ${self:custom.TechsTable.name}
  iamRoleStatements:
    - ${file(iam/TechsTableIAM.yml):TechsTableIAM}

resources:
  Resources:
    TechsTable: ${file(resources/TechsTable.yml):TechsTable}

functions:
  createTech:
    handler: src/handlers/createTech.handler
    events:
      - http:
          method: POST
          path: /techs
          cors: true
          authorizer: ${self:custom.authorizer}

  deleteTech:
    handler: src/handlers/deleteTech.handler
    events:
      - http:
          method: DELETE
          path: /techs/{id}
          cors: true
          authorizer: ${self:custom.authorizer}

  findTechs:
    handler: src/handlers/findTechs.handler
    events:
      - http:
          method: GET
          path: /techs
          cors: true
          authorizer: ${self:custom.authorizer}

  getTech:
    handler: src/handlers/getTech.handler
    events:
      - http:
          method: GET
          path: /techs/{id}
          cors: true
          authorizer: ${self:custom.authorizer}

  updateTech:
    handler: src/handlers/updateTech.handler
    events:
      - http:
          method: PUT
          path: /techs/{id}
          cors: true
          authorizer: ${self:custom.authorizer}

custom:
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
  TechsTable:
    name: !Ref TechsTable
    arn: !GetAtt TechsTable.Arn

package:
  excludeDevDependencies: true
  exclude:
    - tests/**
    - jest.config.ts
